/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import contolador.UsuarioDAO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelo.Usuario;

/**
 *
 * @author clara
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imgUser = new javax.swing.JLabel();
        lblIniSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jpfContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnIngresar1 = new javax.swing.JButton();

        btnIngresar.setBackground(new java.awt.Color(133, 39, 71));
        btnIngresar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");
        setAutoRequestFocus(false);
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setForeground(java.awt.Color.lightGray);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jPanel1.add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 80));

        lblIniSesion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblIniSesion.setText("INICIAR SESIÓN");
        jPanel1.add(lblIniSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jtfUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jtfUsuario.setText("Ingrese su nombre de usuario");
        jtfUsuario.setBorder(null);
        jtfUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfUsuarioMousePressed(evt);
            }
        });
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 290, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 20));

        jpfContraseña.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jpfContraseña.setForeground(new java.awt.Color(102, 102, 102));
        jpfContraseña.setText("********");
        jpfContraseña.setBorder(null);
        jpfContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpfContraseñaMousePressed(evt);
            }
        });
        jpfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jpfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 290, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("EMPRESA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 180, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/building.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 250, 250));

        btnIngresar1.setBackground(new java.awt.Color(133, 39, 71));
        btnIngresar1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnIngresar1.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar1.setText("Ingresar");
        btnIngresar1.setBorder(null);
        btnIngresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresar1MouseClicked(evt);
            }
        });
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jpfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfContraseñaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jtfUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfUsuarioMousePressed
       if (jtfUsuario.getText().equals("Ingrese su nombre de usuario")){
           jtfUsuario.setText("");
           jtfUsuario.setForeground(Color.black);
       }
        
    }//GEN-LAST:event_jtfUsuarioMousePressed

    private void jpfContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpfContraseñaMousePressed
        if(String.valueOf(jpfContraseña.getPassword()).equals("********")){
            jpfContraseña.setText("");
            jpfContraseña.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_jpfContraseñaMousePressed

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarMouseClicked

    
    
    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        if (verificar()) {
            SwingUtilities.invokeLater(new Runnable() {
		@Override
                public void run() {
                    new VentanaPrincipal().setVisible(true);				
                }
            });
            setVisible(false);
	}else {
            JOptionPane.showMessageDialog(null, "El nombre de usuario o la contraseña son incorrectos");
	}
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    
    
    private void btnIngresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar1MouseClicked

    /**
     * @param args the command line arguments
     */
    //public stat
    
    public boolean verificar() {
	try {
            UsuarioDAO uDAO = new UsuarioDAO();
            ArrayList<Usuario> listaUsuarios = uDAO.buscarUsuario("SELECT * FROM Usuario WHERE Nombre = '"+jtfUsuario.getText()+"'");
			uDAO.setFiltro("SELECT * FROM Usuario WHERE nombre = '"+jtfUsuario.getText()+"'");
            if (listaUsuarios.size()!=0) {
		Usuario usuario = listaUsuarios.get(0);
		return usuario.getContraseña().equals(jpfContraseña.getText());
            }
	} catch (NullPointerException e) {
            e.printStackTrace();
	}
	return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JLabel imgUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jpfContraseña;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIniSesion;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
