/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

//import contolador.ProyectoDAO;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
//import modelo.Proyecto;
//import modelo.Grafica;



/**
 *
 * @author clara
 */
public class MenuShippers extends javax.swing.JPanel {

    private Component rootPane;
    String sqlP = "SELECT * FROM proyecto";

    /**
     * Creates new form MenuEmpleado1
     */
    public MenuShippers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpContenidoABCC = new javax.swing.JTabbedPane();
        jpAltas = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ShiperID = new javax.swing.JLabel();
        jtfShipperID = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        CompanyName = new javax.swing.JLabel();
        jtfCompanyName = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Phone = new javax.swing.JLabel();
        jtfPhone = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jpBajas = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ShipperID1 = new javax.swing.JLabel();
        jtfShipperID1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        btnBorrar1 = new javax.swing.JButton();
        jpCambios = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnGuardar2 = new javax.swing.JButton();
        btnBorrar2 = new javax.swing.JButton();
        ShiperID2 = new javax.swing.JLabel();
        jtfShipperID2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        CompanyName2 = new javax.swing.JLabel();
        jtfCompanyName2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Phone2 = new javax.swing.JLabel();
        jtfPhone2 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jpConsultas = new javax.swing.JPanel();
        Titulo3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnBorrar3 = new javax.swing.JButton();
        ShiperID3 = new javax.swing.JLabel();
        jtfShipperID3 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        CompanyName3 = new javax.swing.JLabel();
        jtfCompanyName3 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Phone3 = new javax.swing.JLabel();
        jtfPhone3 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jpGrafica = new javax.swing.JPanel();
        btnGenerarG = new javax.swing.JButton();
        jpTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 198, 165));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(162, 65, 107));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Shippers");

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(840, Short.MAX_VALUE))
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 100));

        jtpContenidoABCC.setBackground(new java.awt.Color(245, 198, 165));
        jtpContenidoABCC.setForeground(new java.awt.Color(102, 102, 102));
        jtpContenidoABCC.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtpContenidoABCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpContenidoABCCMouseClicked(evt);
            }
        });

        jpAltas.setBackground(new java.awt.Color(245, 198, 165));
        jpAltas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Add shipper");
        jpAltas.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 30, 500, 41));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 21));

        ShiperID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ShiperID.setForeground(new java.awt.Color(102, 102, 102));
        ShiperID.setText("Shipper ID");
        jpAltas.add(ShiperID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        jtfShipperID.setBackground(new java.awt.Color(245, 198, 165));
        jtfShipperID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfShipperID.setBorder(null);
        jtfShipperID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfShipperIDActionPerformed(evt);
            }
        });
        jtfShipperID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfShipperIDKeyPressed(evt);
            }
        });
        jpAltas.add(jtfShipperID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 50, 30));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 50, 20));

        CompanyName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CompanyName.setForeground(new java.awt.Color(102, 102, 102));
        CompanyName.setText("Company Name");
        jpAltas.add(CompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 30));

        jtfCompanyName.setBackground(new java.awt.Color(245, 198, 165));
        jtfCompanyName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCompanyName.setBorder(null);
        jtfCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyNameActionPerformed(evt);
            }
        });
        jtfCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCompanyNameKeyPressed(evt);
            }
        });
        jpAltas.add(jtfCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 159, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 159, 20));

        Phone.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Phone.setForeground(new java.awt.Color(102, 102, 102));
        Phone.setText("Phone");
        jpAltas.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, 30));

        jtfPhone.setBackground(new java.awt.Color(245, 198, 165));
        jtfPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPhone.setBorder(null);
        jtfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPhoneActionPerformed(evt);
            }
        });
        jtfPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPhoneKeyPressed(evt);
            }
        });
        jpAltas.add(jtfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 130, 30));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 120, 20));

        btnAgregar.setBackground(new java.awt.Color(162, 65, 107));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpAltas.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 120, 30));

        btnBorrar.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jpAltas.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 120, 30));

        jtpContenidoABCC.addTab("Altas", jpAltas);

        jpBajas.setBackground(new java.awt.Color(245, 198, 165));
        jpBajas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Delete shipper");
        jpBajas.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 30, 500, 41));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jpBajas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 21));

        ShipperID1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ShipperID1.setForeground(new java.awt.Color(102, 102, 102));
        ShipperID1.setText("Shipper ID");
        jpBajas.add(ShipperID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        jtfShipperID1.setBackground(new java.awt.Color(245, 198, 165));
        jtfShipperID1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfShipperID1.setBorder(null);
        jtfShipperID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfShipperID1ActionPerformed(evt);
            }
        });
        jtfShipperID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfShipperID1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfShipperID1KeyReleased(evt);
            }
        });
        jpBajas.add(jtfShipperID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 50, 30));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jpBajas.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, 20));

        btnEliminar.setBackground(new java.awt.Color(162, 65, 107));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpBajas.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 120, 30));

        btnBorrar1.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar1.setText("Borrar");
        btnBorrar1.setBorder(null);
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        jpBajas.add(btnBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 120, 30));

        jtpContenidoABCC.addTab("Bajas", jpBajas);

        jpCambios.setBackground(new java.awt.Color(245, 198, 165));
        jpCambios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Modify shipper");
        jpCambios.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 30, 500, 41));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 21));

        btnGuardar2.setBackground(new java.awt.Color(162, 65, 107));
        btnGuardar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setText("Guardar cambios");
        btnGuardar2.setBorder(null);
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 160, 30));

        btnBorrar2.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar2.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar2.setText("Borrar");
        btnBorrar2.setBorder(null);
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 120, 30));

        ShiperID2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ShiperID2.setForeground(new java.awt.Color(102, 102, 102));
        ShiperID2.setText("Shipper ID");
        jpCambios.add(ShiperID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        jtfShipperID2.setBackground(new java.awt.Color(245, 198, 165));
        jtfShipperID2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfShipperID2.setBorder(null);
        jtfShipperID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfShipperID2ActionPerformed(evt);
            }
        });
        jtfShipperID2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfShipperID2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfShipperID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 50, 30));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 50, 20));

        CompanyName2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CompanyName2.setForeground(new java.awt.Color(102, 102, 102));
        CompanyName2.setText("Company Name");
        jpCambios.add(CompanyName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 30));

        jtfCompanyName2.setBackground(new java.awt.Color(245, 198, 165));
        jtfCompanyName2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCompanyName2.setBorder(null);
        jtfCompanyName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyName2ActionPerformed(evt);
            }
        });
        jtfCompanyName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCompanyName2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfCompanyName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 159, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 159, 20));

        Phone2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Phone2.setForeground(new java.awt.Color(102, 102, 102));
        Phone2.setText("Phone");
        jpCambios.add(Phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, 30));

        jtfPhone2.setBackground(new java.awt.Color(245, 198, 165));
        jtfPhone2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPhone2.setBorder(null);
        jtfPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPhone2ActionPerformed(evt);
            }
        });
        jtfPhone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPhone2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 130, 30));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 120, 20));

        jtpContenidoABCC.addTab("Cambios", jpCambios);

        jpConsultas.setBackground(new java.awt.Color(245, 198, 165));
        jpConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo3.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(255, 255, 255));
        Titulo3.setText("Search shipper");
        jpConsultas.add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 500, 41));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 840, 21));

        btnBorrar3.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar3.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar3.setText("Borrar");
        btnBorrar3.setBorder(null);
        btnBorrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar3ActionPerformed(evt);
            }
        });
        jpConsultas.add(btnBorrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, 30));

        ShiperID3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ShiperID3.setForeground(new java.awt.Color(102, 102, 102));
        ShiperID3.setText("Shipper ID");
        jpConsultas.add(ShiperID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        jtfShipperID3.setBackground(new java.awt.Color(245, 198, 165));
        jtfShipperID3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfShipperID3.setBorder(null);
        jtfShipperID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfShipperID3ActionPerformed(evt);
            }
        });
        jtfShipperID3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfShipperID3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfShipperID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 50, 30));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 50, 20));

        CompanyName3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CompanyName3.setForeground(new java.awt.Color(102, 102, 102));
        CompanyName3.setText("Company Name");
        jpConsultas.add(CompanyName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 30));

        jtfCompanyName3.setBackground(new java.awt.Color(245, 198, 165));
        jtfCompanyName3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCompanyName3.setBorder(null);
        jtfCompanyName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyName3ActionPerformed(evt);
            }
        });
        jtfCompanyName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCompanyName3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfCompanyName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 159, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 159, 20));

        Phone3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Phone3.setForeground(new java.awt.Color(102, 102, 102));
        Phone3.setText("Phone");
        jpConsultas.add(Phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, 30));

        jtfPhone3.setBackground(new java.awt.Color(245, 198, 165));
        jtfPhone3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPhone3.setBorder(null);
        jtfPhone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPhone3ActionPerformed(evt);
            }
        });
        jtfPhone3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPhone3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfPhone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 130, 30));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 120, 20));

        jtpContenidoABCC.addTab("Consultas", jpConsultas);

        jpGrafica.setBackground(new java.awt.Color(245, 198, 165));
        jpGrafica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerarG.setBackground(new java.awt.Color(162, 65, 107));
        btnGenerarG.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGenerarG.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarG.setText("Generar gráfica");
        btnGenerarG.setBorder(null);
        btnGenerarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarGActionPerformed(evt);
            }
        });
        jpGrafica.add(btnGenerarG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 140, 40));

        jtpContenidoABCC.addTab("Gráfica", jpGrafica);

        add(jtpContenidoABCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 960, 330));

        jpTabla.setBackground(new java.awt.Color(255, 255, 255));
        jpTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 880, 230));

        add(jpTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 960, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        /*ProyectoDAO pDAO = new ProyectoDAO();
        if(jtfNumProyecto1.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane,"Debes ingresar el número de proyecto");
	}else {
             byte num = Byte.parseByte(jtfNumProyecto1.getText());
            if(pDAO.eliminarRegistro(num)) {
                JOptionPane.showMessageDialog(rootPane,"Se eliminó correctamente de la base de datos");
            }else{
                 JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar eliminar a la base de datos");
            }
           
	}
        mostrarTabla(sqlP);*/
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        /*ProyectoDAO pDAO = new ProyectoDAO();
        if(jtfNomProyecto2.getText().equals("")||jtfNumProyecto2.getText().equals("")||
                jtfUbiProyecto2.getText().equals("")||jtfNumDptoProyecto2.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar los campos");
        }else{
            Proyecto p = new Proyecto(jtfNomProyecto2.getText(),Integer.parseInt(jtfNumProyecto2.getText()),
            jtfUbiProyecto2.getText(),Byte.parseByte(jtfNumDptoProyecto2.getText()));
            if(pDAO.modificarRegistro(p)){
                JOptionPane.showMessageDialog(rootPane, "Datos modificados exitosamente");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudieron modificar los datos");
            }
            mostrarTabla(sqlP);*/
        //}
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        restablecerComponentes(jtfShipperID2,jtfCompanyName2,jtfPhone2);
    }//GEN-LAST:event_btnBorrar2ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        restablecerComponentes(jtfShipperID,jtfCompanyName,jtfPhone);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jtfShipperID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfShipperID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfShipperID1ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        restablecerComponentes(jtfShipperID1);
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        /*ProyectoDAO pDAO = new ProyectoDAO();
        if(jtfNomProyecto.getText().equals("")||jtfNumProyecto.getText().equals("")||
                jtfUbiProyecto.getText().equals("")||jtfNumDptoProyecto.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar los campos");
        }else{
            Proyecto p = new Proyecto(jtfNomProyecto.getText(),Integer.parseInt(jtfNumProyecto.getText()),
            jtfUbiProyecto.getText(),Byte.parseByte(jtfNumDptoProyecto.getText()));
            
            if(pDAO.insertarRragistro(p)){
                JOptionPane.showMessageDialog(rootPane,"Se agregó correctamente a la base de datos");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar agregar a la base de datos");
            }
            
        }
        mostrarTabla(sqlP);*/
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtfShipperIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfShipperIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfShipperIDActionPerformed

    private void jtfCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyNameActionPerformed
        //if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9')||(code==KeyEvent.VK_BACK_SPACE)) {}
        
    }//GEN-LAST:event_jtfCompanyNameActionPerformed

    private void jtpContenidoABCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpContenidoABCCMouseClicked
        mostrarTabla(sqlP);
        mostrarTabla2();
    }//GEN-LAST:event_jtpContenidoABCCMouseClicked

    private void jtfCompanyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyNameKeyPressed
        validacionLetras(evt,jtfCompanyName);
    }//GEN-LAST:event_jtfCompanyNameKeyPressed

    private void jtfShipperIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfShipperIDKeyPressed
        validacionNumeros(evt, jtfShipperID, 1);
    }//GEN-LAST:event_jtfShipperIDKeyPressed

    private void btnGenerarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarGActionPerformed
       /*Grafica g = new Grafica();
     
       if(g.dibujar()!=null){
           jpGrafica.setLayout(new BorderLayout());
           jpGrafica.add(g.dibujar(),new BorderLayout().NORTH);
           
       }else{
           System.out.println("No funciona");
       }*/
        
    }//GEN-LAST:event_btnGenerarGActionPerformed

    private void btnBorrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar3ActionPerformed
         restablecerComponentes(jtfShipperID3,jtfCompanyName3,jtfPhone3);
    }//GEN-LAST:event_btnBorrar3ActionPerformed

    private void jtfShipperID1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfShipperID1KeyPressed
        validacionNumeros(evt, jtfShipperID1, 1);
    }//GEN-LAST:event_jtfShipperID1KeyPressed

    private void jtfShipperID1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfShipperID1KeyReleased
        String filtro = jtfShipperID1.getText();
        String sql =  "SELECT * FROM proyecto WHERE NumProyecto LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfShipperID1KeyReleased

    private void jtfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhoneActionPerformed

    private void jtfPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhoneKeyPressed

    private void jtfShipperID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfShipperID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfShipperID2ActionPerformed

    private void jtfShipperID2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfShipperID2KeyPressed
        validacionNumeros(evt, jtfShipperID2, 1);
    }//GEN-LAST:event_jtfShipperID2KeyPressed

    private void jtfCompanyName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName2ActionPerformed

    private void jtfCompanyName2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyName2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName2KeyPressed

    private void jtfPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone2ActionPerformed

    private void jtfPhone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhone2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone2KeyPressed

    private void jtfShipperID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfShipperID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfShipperID3ActionPerformed

    private void jtfShipperID3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfShipperID3KeyPressed
        validacionNumeros(evt, jtfShipperID3, 1);
    }//GEN-LAST:event_jtfShipperID3KeyPressed

    private void jtfCompanyName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName3ActionPerformed

    private void jtfCompanyName3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyName3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName3KeyPressed

    private void jtfPhone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPhone3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone3ActionPerformed

    private void jtfPhone3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhone3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone3KeyPressed

    
    
    public void restablecerComponentes(Component...componentesGraficos) {
	for (Component c: componentesGraficos) {
            if (c instanceof JTextField) {
		((JTextField)c).setText("");
            }
        }
    }
    
    public void mostrarTabla(String sql){
        /*ResultSetTableModel modeloDatos = null;
	try {
            modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/empresa",sql);
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane1.getViewport().remove(jTable1);
        jTable1 = new JTable(modeloDatos);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla();
            }
        });
        jScrollPane1.getViewport().add(jTable1);*/
        
    }
    
    
    public void obtenerRegistroTabla(){
        
        
    }
    
    public void mostrarTabla2(){
        /*ResultSetTableModel modeloDatos = null;
	try {
            modeloDatos = new ResultSetTableModel("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/empresa","SELECT * FROM localizaciones_dpto");
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane2.getViewport().remove(jTable2);
        jTable2 = new JTable(modeloDatos);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla2();
            }
        });
        jScrollPane2.getViewport().add(jTable2);*/
        
    }
    
    
    public void validacionLetras(KeyEvent evt, JTextField jtf){  
        char car = evt.getKeyChar();
	if(Character.isLetter(car)||(car==KeyEvent.VK_BACK_SPACE)){
            jtf.setEditable(true);
        }else{
            jtf.setEditable(false);
        }
    }
    
    public void validacionNumeros(KeyEvent evt, JTextField jtf, int limite){
        int code=evt.getKeyCode();
        //int limite=3;    
        if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&jtf.getText().length()<limite||(code==KeyEvent.VK_BACK_SPACE)) {
            jtf.setEditable(true);
        }else{
            jtf.setEditable(false);
        }  
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompanyName;
    private javax.swing.JLabel CompanyName2;
    private javax.swing.JLabel CompanyName3;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Phone2;
    private javax.swing.JLabel Phone3;
    private javax.swing.JLabel ShiperID;
    private javax.swing.JLabel ShiperID2;
    private javax.swing.JLabel ShiperID3;
    private javax.swing.JLabel ShipperID1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnBorrar3;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarG;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpAltas;
    private javax.swing.JPanel jpBajas;
    private javax.swing.JPanel jpCambios;
    private javax.swing.JPanel jpConsultas;
    private javax.swing.JPanel jpGrafica;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JTextField jtfCompanyName;
    private javax.swing.JTextField jtfCompanyName2;
    private javax.swing.JTextField jtfCompanyName3;
    private javax.swing.JTextField jtfPhone;
    private javax.swing.JTextField jtfPhone2;
    private javax.swing.JTextField jtfPhone3;
    private javax.swing.JTextField jtfShipperID;
    private javax.swing.JTextField jtfShipperID1;
    private javax.swing.JTextField jtfShipperID2;
    private javax.swing.JTextField jtfShipperID3;
    private javax.swing.JTabbedPane jtpContenidoABCC;
    // End of variables declaration//GEN-END:variables
}
