/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.CustomerDAO;
import controlador.ShipperDAO;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import modelo.Customers;

/**
 *
 * @author clara
 */
public class MenuCustomers extends javax.swing.JPanel {

    /**
     * Creates new form MenuEmpleado1
     */
    String sqlC = "SELECT * FROM customers";
    private Component rootPane;
    
    public MenuCustomers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpContenidoABCC = new javax.swing.JTabbedPane();
        jpAltas = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CustomerID = new javax.swing.JLabel();
        jtfCustomerID = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        CompanyName = new javax.swing.JLabel();
        jtfCompanyName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        ContactName = new javax.swing.JLabel();
        jtfContactName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        ContactTitle = new javax.swing.JLabel();
        jtfContactTitle = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Address = new javax.swing.JLabel();
        jtfAddress = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        City = new javax.swing.JLabel();
        jtfCity = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Region = new javax.swing.JLabel();
        jtfRegion = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        PostalCode = new javax.swing.JLabel();
        jtfPostalCode = new javax.swing.JTextField();
        jSeparator32 = new javax.swing.JSeparator();
        Country = new javax.swing.JLabel();
        jtfCountry = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Phone = new javax.swing.JLabel();
        jtfPhone = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Fax = new javax.swing.JLabel();
        jtfFax = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jpBajas = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        CustomerID1 = new javax.swing.JLabel();
        jtfCustomerID1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        btnBorrar1 = new javax.swing.JButton();
        jpCambios = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        btnGuardar2 = new javax.swing.JButton();
        btnBorrar2 = new javax.swing.JButton();
        CustomerID2 = new javax.swing.JLabel();
        jtfCustomerID2 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        CompanyName2 = new javax.swing.JLabel();
        jtfCompanyName2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        ContactName2 = new javax.swing.JLabel();
        jtfContactName2 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        ContactTitle2 = new javax.swing.JLabel();
        jtfContactTitle2 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        Address2 = new javax.swing.JLabel();
        jtfAddress2 = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        City2 = new javax.swing.JLabel();
        jtfCity2 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        Region2 = new javax.swing.JLabel();
        jtfRegion2 = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        PostalCode2 = new javax.swing.JLabel();
        jtfPostalCode2 = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        Country2 = new javax.swing.JLabel();
        jtfCountry2 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        Phone2 = new javax.swing.JLabel();
        jtfPhone2 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        Fax2 = new javax.swing.JLabel();
        jtfFax2 = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        jpConsultas = new javax.swing.JPanel();
        Titulo3 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        btnBorrar3 = new javax.swing.JButton();
        CustomerID3 = new javax.swing.JLabel();
        jtfCustomerID3 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        CompanyName3 = new javax.swing.JLabel();
        jtfCompanyName3 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        ContactName3 = new javax.swing.JLabel();
        jtfContactName3 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        ContactTitle3 = new javax.swing.JLabel();
        jtfContactTitle3 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        Address3 = new javax.swing.JLabel();
        jtfAddress3 = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();
        City3 = new javax.swing.JLabel();
        jtfCity3 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        Region3 = new javax.swing.JLabel();
        jtfRegion3 = new javax.swing.JTextField();
        jSeparator39 = new javax.swing.JSeparator();
        PostalCode3 = new javax.swing.JLabel();
        jtfPostalCode3 = new javax.swing.JTextField();
        jSeparator40 = new javax.swing.JSeparator();
        Country3 = new javax.swing.JLabel();
        jtfCountry3 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        Phone3 = new javax.swing.JLabel();
        jtfPhone3 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        Fax3 = new javax.swing.JLabel();
        jtfFax3 = new javax.swing.JTextField();
        jSeparator41 = new javax.swing.JSeparator();
        jpTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 205, 185));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(162, 65, 107));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customers");

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTituloLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 100));

        jtpContenidoABCC.setBackground(new java.awt.Color(245, 205, 185));
        jtpContenidoABCC.setForeground(new java.awt.Color(102, 102, 102));
        jtpContenidoABCC.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtpContenidoABCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpContenidoABCCMouseClicked(evt);
            }
        });
        jtpContenidoABCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpContenidoABCCKeyPressed(evt);
            }
        });

        jpAltas.setBackground(new java.awt.Color(245, 205, 185));
        jpAltas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpAltas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Add customer");
        jpAltas.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        CustomerID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CustomerID.setForeground(new java.awt.Color(102, 102, 102));
        CustomerID.setText("Customer ID");
        jpAltas.add(CustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtfCustomerID.setBackground(new java.awt.Color(245, 205, 185));
        jtfCustomerID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCustomerID.setBorder(null);
        jtfCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCustomerIDActionPerformed(evt);
            }
        });
        jtfCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCustomerIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCustomerIDKeyTyped(evt);
            }
        });
        jpAltas.add(jtfCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 110, 70, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 140, 70, 20));

        CompanyName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CompanyName.setForeground(new java.awt.Color(102, 102, 102));
        CompanyName.setText("Company Name");
        jpAltas.add(CompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        jtfCompanyName.setBackground(new java.awt.Color(245, 205, 185));
        jtfCompanyName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCompanyName.setBorder(null);
        jtfCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyNameActionPerformed(evt);
            }
        });
        jtfCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCompanyNameKeyPressed(evt);
            }
        });
        jpAltas.add(jtfCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 210, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 210, 20));

        ContactName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ContactName.setForeground(new java.awt.Color(102, 102, 102));
        ContactName.setText("Contact Name");
        jpAltas.add(ContactName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        jtfContactName.setBackground(new java.awt.Color(245, 205, 185));
        jtfContactName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfContactName.setBorder(null);
        jtfContactName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContactNameKeyPressed(evt);
            }
        });
        jpAltas.add(jtfContactName, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 110, 170, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 140, 170, 20));

        ContactTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ContactTitle.setForeground(new java.awt.Color(102, 102, 102));
        ContactTitle.setText("Contact Title");
        jpAltas.add(ContactTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jtfContactTitle.setBackground(new java.awt.Color(245, 205, 185));
        jtfContactTitle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfContactTitle.setBorder(null);
        jtfContactTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContactTitleKeyPressed(evt);
            }
        });
        jpAltas.add(jtfContactTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 20));

        Address.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(102, 102, 102));
        Address.setText("Address");
        jpAltas.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 30));

        jtfAddress.setBackground(new java.awt.Color(245, 205, 185));
        jtfAddress.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAddress.setBorder(null);
        jtfAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAddressKeyPressed(evt);
            }
        });
        jpAltas.add(jtfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, 30));

        jSeparator30.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 170, 20));

        City.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        City.setForeground(new java.awt.Color(102, 102, 102));
        City.setText("City");
        jpAltas.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, 30));

        jtfCity.setBackground(new java.awt.Color(245, 205, 185));
        jtfCity.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCity.setBorder(null);
        jtfCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCityKeyPressed(evt);
            }
        });
        jpAltas.add(jtfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 80, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 80, 20));

        Region.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Region.setForeground(new java.awt.Color(102, 102, 102));
        Region.setText("Region");
        jpAltas.add(Region, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, 30));

        jtfRegion.setBackground(new java.awt.Color(245, 205, 185));
        jtfRegion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfRegion.setBorder(null);
        jtfRegion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfRegionKeyPressed(evt);
            }
        });
        jpAltas.add(jtfRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 60, 30));

        jSeparator31.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 60, 20));

        PostalCode.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PostalCode.setForeground(new java.awt.Color(102, 102, 102));
        PostalCode.setText("Postal code");
        jpAltas.add(PostalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jtfPostalCode.setBackground(new java.awt.Color(245, 205, 185));
        jtfPostalCode.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPostalCode.setBorder(null);
        jtfPostalCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPostalCodeKeyPressed(evt);
            }
        });
        jpAltas.add(jtfPostalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 30));

        jSeparator32.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 90, 20));

        Country.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Country.setForeground(new java.awt.Color(102, 102, 102));
        Country.setText("Country");
        jpAltas.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        jtfCountry.setBackground(new java.awt.Color(245, 205, 185));
        jtfCountry.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCountry.setBorder(null);
        jtfCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCountryKeyPressed(evt);
            }
        });
        jpAltas.add(jtfCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 90, 20));

        Phone.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Phone.setForeground(new java.awt.Color(102, 102, 102));
        Phone.setText("Phone");
        jpAltas.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 30));

        jtfPhone.setBackground(new java.awt.Color(245, 205, 185));
        jtfPhone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPhone.setBorder(null);
        jtfPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPhoneKeyReleased(evt);
            }
        });
        jpAltas.add(jtfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, 30));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 150, 20));

        Fax.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Fax.setForeground(new java.awt.Color(102, 102, 102));
        Fax.setText("Fax");
        jpAltas.add(Fax, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, 30));

        jtfFax.setBackground(new java.awt.Color(245, 205, 185));
        jtfFax.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfFax.setBorder(null);
        jtfFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfFaxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFaxKeyReleased(evt);
            }
        });
        jpAltas.add(jtfFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 150, 30));

        jSeparator33.setForeground(new java.awt.Color(255, 255, 255));
        jpAltas.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 150, 20));

        btnAgregar.setBackground(new java.awt.Color(162, 65, 107));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jpAltas.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 120, 30));

        btnBorrar.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jpAltas.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 120, 30));

        jtpContenidoABCC.addTab("Altas", jpAltas);

        jpBajas.setBackground(new java.awt.Color(245, 205, 185));
        jpBajas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setBackground(new java.awt.Color(255, 255, 255));
        Titulo1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Delete customer");
        jpBajas.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jpBajas.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        CustomerID1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CustomerID1.setForeground(new java.awt.Color(102, 102, 102));
        CustomerID1.setText("Customer ID");
        jpBajas.add(CustomerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        jtfCustomerID1.setBackground(new java.awt.Color(245, 205, 185));
        jtfCustomerID1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCustomerID1.setBorder(null);
        jtfCustomerID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCustomerID1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCustomerID1KeyReleased(evt);
            }
        });
        jpBajas.add(jtfCustomerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 130, 100, 30));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jpBajas.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 160, 100, 20));

        btnEliminar.setBackground(new java.awt.Color(162, 65, 107));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpBajas.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 120, 30));

        btnBorrar1.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar1.setText("Borrar");
        btnBorrar1.setBorder(null);
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        jpBajas.add(btnBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 120, 30));

        jtpContenidoABCC.addTab("Bajas", jpBajas);

        jpCambios.setBackground(new java.awt.Color(245, 205, 185));
        jpCambios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo2.setBackground(new java.awt.Color(255, 255, 255));
        Titulo2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Modify customer");
        jpCambios.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        btnGuardar2.setBackground(new java.awt.Color(162, 65, 107));
        btnGuardar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setText("Guardar cambios");
        btnGuardar2.setBorder(null);
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 160, 30));

        btnBorrar2.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar2.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar2.setText("Borrar");
        btnBorrar2.setBorder(null);
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });
        jpCambios.add(btnBorrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 120, 30));

        CustomerID2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CustomerID2.setForeground(new java.awt.Color(102, 102, 102));
        CustomerID2.setText("Customer ID");
        jpCambios.add(CustomerID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtfCustomerID2.setBackground(new java.awt.Color(245, 205, 185));
        jtfCustomerID2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCustomerID2.setBorder(null);
        jtfCustomerID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCustomerID2ActionPerformed(evt);
            }
        });
        jtfCustomerID2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCustomerID2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCustomerID2KeyTyped(evt);
            }
        });
        jpCambios.add(jtfCustomerID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 110, 70, 30));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 140, 70, 20));

        CompanyName2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CompanyName2.setForeground(new java.awt.Color(102, 102, 102));
        CompanyName2.setText("Company Name");
        jpCambios.add(CompanyName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        jtfCompanyName2.setBackground(new java.awt.Color(245, 205, 185));
        jtfCompanyName2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCompanyName2.setBorder(null);
        jtfCompanyName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyName2ActionPerformed(evt);
            }
        });
        jtfCompanyName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCompanyName2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfCompanyName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 210, 30));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 210, 20));

        ContactName2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ContactName2.setForeground(new java.awt.Color(102, 102, 102));
        ContactName2.setText("Contact Name");
        jpCambios.add(ContactName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        jtfContactName2.setBackground(new java.awt.Color(245, 205, 185));
        jtfContactName2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfContactName2.setBorder(null);
        jtfContactName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContactName2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfContactName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 110, 170, 30));

        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 140, 170, 20));

        ContactTitle2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ContactTitle2.setForeground(new java.awt.Color(102, 102, 102));
        ContactTitle2.setText("Contact Title");
        jpCambios.add(ContactTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jtfContactTitle2.setBackground(new java.awt.Color(245, 205, 185));
        jtfContactTitle2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfContactTitle2.setBorder(null);
        jtfContactTitle2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContactTitle2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfContactTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 30));

        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 20));

        Address2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Address2.setForeground(new java.awt.Color(102, 102, 102));
        Address2.setText("Address");
        jpCambios.add(Address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 30));

        jtfAddress2.setBackground(new java.awt.Color(245, 205, 185));
        jtfAddress2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAddress2.setBorder(null);
        jtfAddress2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAddress2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, 30));

        jSeparator34.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 170, 20));

        City2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        City2.setForeground(new java.awt.Color(102, 102, 102));
        City2.setText("City");
        jpCambios.add(City2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, 30));

        jtfCity2.setBackground(new java.awt.Color(245, 205, 185));
        jtfCity2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCity2.setBorder(null);
        jtfCity2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCity2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfCity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 80, 30));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 80, 20));

        Region2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Region2.setForeground(new java.awt.Color(102, 102, 102));
        Region2.setText("Region");
        jpCambios.add(Region2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, 30));

        jtfRegion2.setBackground(new java.awt.Color(245, 205, 185));
        jtfRegion2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfRegion2.setBorder(null);
        jtfRegion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfRegion2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfRegion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 60, 30));

        jSeparator35.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 60, 20));

        PostalCode2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PostalCode2.setForeground(new java.awt.Color(102, 102, 102));
        PostalCode2.setText("Postal code");
        jpCambios.add(PostalCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jtfPostalCode2.setBackground(new java.awt.Color(245, 205, 185));
        jtfPostalCode2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPostalCode2.setBorder(null);
        jtfPostalCode2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPostalCode2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfPostalCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 30));

        jSeparator36.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 90, 20));

        Country2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Country2.setForeground(new java.awt.Color(102, 102, 102));
        Country2.setText("Country");
        jpCambios.add(Country2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        jtfCountry2.setBackground(new java.awt.Color(245, 205, 185));
        jtfCountry2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCountry2.setBorder(null);
        jtfCountry2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCountry2KeyPressed(evt);
            }
        });
        jpCambios.add(jtfCountry2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, 30));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 90, 20));

        Phone2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Phone2.setForeground(new java.awt.Color(102, 102, 102));
        Phone2.setText("Phone");
        jpCambios.add(Phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 30));

        jtfPhone2.setBackground(new java.awt.Color(245, 205, 185));
        jtfPhone2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPhone2.setBorder(null);
        jtfPhone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPhone2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPhone2KeyReleased(evt);
            }
        });
        jpCambios.add(jtfPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, 30));

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 150, 20));

        Fax2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Fax2.setForeground(new java.awt.Color(102, 102, 102));
        Fax2.setText("Fax");
        jpCambios.add(Fax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, 30));

        jtfFax2.setBackground(new java.awt.Color(245, 205, 185));
        jtfFax2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfFax2.setBorder(null);
        jtfFax2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfFax2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFax2KeyReleased(evt);
            }
        });
        jpCambios.add(jtfFax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 150, 30));

        jSeparator37.setForeground(new java.awt.Color(255, 255, 255));
        jpCambios.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 150, 20));

        jtpContenidoABCC.addTab("Cambios", jpCambios);

        jpConsultas.setBackground(new java.awt.Color(245, 205, 185));
        jpConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo3.setBackground(new java.awt.Color(255, 255, 255));
        Titulo3.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(255, 255, 255));
        Titulo3.setText("Search customer");
        jpConsultas.add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 41));

        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 880, 21));

        btnBorrar3.setBackground(new java.awt.Color(162, 65, 107));
        btnBorrar3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnBorrar3.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar3.setText("Borrar");
        btnBorrar3.setBorder(null);
        btnBorrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar3ActionPerformed(evt);
            }
        });
        jpConsultas.add(btnBorrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, 30));

        CustomerID3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CustomerID3.setForeground(new java.awt.Color(102, 102, 102));
        CustomerID3.setText("Customer ID");
        jpConsultas.add(CustomerID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jtfCustomerID3.setBackground(new java.awt.Color(245, 205, 185));
        jtfCustomerID3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCustomerID3.setBorder(null);
        jtfCustomerID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCustomerID3ActionPerformed(evt);
            }
        });
        jtfCustomerID3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCustomerID3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCustomerID3KeyTyped(evt);
            }
        });
        jpConsultas.add(jtfCustomerID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 110, 70, 30));

        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 140, 70, 20));

        CompanyName3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CompanyName3.setForeground(new java.awt.Color(102, 102, 102));
        CompanyName3.setText("Company Name");
        jpConsultas.add(CompanyName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        jtfCompanyName3.setBackground(new java.awt.Color(245, 205, 185));
        jtfCompanyName3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCompanyName3.setBorder(null);
        jtfCompanyName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyName3ActionPerformed(evt);
            }
        });
        jtfCompanyName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCompanyName3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfCompanyName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 210, 30));

        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 210, 20));

        ContactName3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ContactName3.setForeground(new java.awt.Color(102, 102, 102));
        ContactName3.setText("Contact Name");
        jpConsultas.add(ContactName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        jtfContactName3.setBackground(new java.awt.Color(245, 205, 185));
        jtfContactName3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfContactName3.setBorder(null);
        jtfContactName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContactName3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfContactName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 110, 170, 30));

        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 140, 170, 20));

        ContactTitle3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ContactTitle3.setForeground(new java.awt.Color(102, 102, 102));
        ContactTitle3.setText("Contact Title");
        jpConsultas.add(ContactTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jtfContactTitle3.setBackground(new java.awt.Color(245, 205, 185));
        jtfContactTitle3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfContactTitle3.setBorder(null);
        jtfContactTitle3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfContactTitle3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfContactTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 30));

        jSeparator23.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, 20));

        Address3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Address3.setForeground(new java.awt.Color(102, 102, 102));
        Address3.setText("Address");
        jpConsultas.add(Address3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 30));

        jtfAddress3.setBackground(new java.awt.Color(245, 205, 185));
        jtfAddress3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfAddress3.setBorder(null);
        jtfAddress3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAddress3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfAddress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, 30));

        jSeparator38.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 170, 20));

        City3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        City3.setForeground(new java.awt.Color(102, 102, 102));
        City3.setText("City");
        jpConsultas.add(City3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, 30));

        jtfCity3.setBackground(new java.awt.Color(245, 205, 185));
        jtfCity3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCity3.setBorder(null);
        jtfCity3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCity3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfCity3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 80, 30));

        jSeparator24.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 80, 20));

        Region3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Region3.setForeground(new java.awt.Color(102, 102, 102));
        Region3.setText("Region");
        jpConsultas.add(Region3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, 30));

        jtfRegion3.setBackground(new java.awt.Color(245, 205, 185));
        jtfRegion3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfRegion3.setBorder(null);
        jtfRegion3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfRegion3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfRegion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 60, 30));

        jSeparator39.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 60, 20));

        PostalCode3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PostalCode3.setForeground(new java.awt.Color(102, 102, 102));
        PostalCode3.setText("Postal code");
        jpConsultas.add(PostalCode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jtfPostalCode3.setBackground(new java.awt.Color(245, 205, 185));
        jtfPostalCode3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPostalCode3.setBorder(null);
        jtfPostalCode3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPostalCode3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfPostalCode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 90, 30));

        jSeparator40.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 90, 20));

        Country3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Country3.setForeground(new java.awt.Color(102, 102, 102));
        Country3.setText("Country");
        jpConsultas.add(Country3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        jtfCountry3.setBackground(new java.awt.Color(245, 205, 185));
        jtfCountry3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfCountry3.setBorder(null);
        jtfCountry3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCountry3KeyPressed(evt);
            }
        });
        jpConsultas.add(jtfCountry3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, 30));

        jSeparator25.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 90, 20));

        Phone3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Phone3.setForeground(new java.awt.Color(102, 102, 102));
        Phone3.setText("Phone");
        jpConsultas.add(Phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 30));

        jtfPhone3.setBackground(new java.awt.Color(245, 205, 185));
        jtfPhone3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfPhone3.setBorder(null);
        jtfPhone3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPhone3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPhone3KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfPhone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 150, 30));

        jSeparator26.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 150, 20));

        Fax3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Fax3.setForeground(new java.awt.Color(102, 102, 102));
        Fax3.setText("Fax");
        jpConsultas.add(Fax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, 30));

        jtfFax3.setBackground(new java.awt.Color(245, 205, 185));
        jtfFax3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtfFax3.setBorder(null);
        jtfFax3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfFax3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfFax3KeyReleased(evt);
            }
        });
        jpConsultas.add(jtfFax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 150, 30));

        jSeparator41.setForeground(new java.awt.Color(255, 255, 255));
        jpConsultas.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 150, 20));

        jtpContenidoABCC.addTab("Consultas", jpConsultas);

        add(jtpContenidoABCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 960, 390));

        jpTabla.setBackground(new java.awt.Color(255, 255, 255));
        jpTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 170));

        add(jpTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 960, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void jtpContenidoABCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpContenidoABCCKeyPressed
        mostrarTabla(sqlC);
    }//GEN-LAST:event_jtpContenidoABCCKeyPressed

    private void jtpContenidoABCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpContenidoABCCMouseClicked
        mostrarTabla(sqlC);
    }//GEN-LAST:event_jtpContenidoABCCMouseClicked

    private void btnBorrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar3ActionPerformed
        restablecerComponentes(jtfCustomerID3,jtfCompanyName3,jtfContactName3,jtfContactTitle3,jtfAddress3,jtfCity3,jtfRegion3,
                               jtfPostalCode3,jtfCountry3,jtfPhone3,jtfFax3);
    }//GEN-LAST:event_btnBorrar3ActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        restablecerComponentes(jtfCustomerID2,jtfCompanyName2,jtfContactName2,jtfContactTitle2,jtfAddress2,jtfCity2,jtfRegion2,
                               jtfPostalCode2,jtfCountry2,jtfPhone2,jtfFax2);
    }//GEN-LAST:event_btnBorrar2ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        CustomerDAO cDAO = new CustomerDAO();
        if(jtfCustomerID.getText().equals("")|| jtfCompanyName.getText().equals("")||jtfContactName.getText().equals("")
                ||jtfContactTitle.getText().equals("")||jtfAddress.getText().equals("")||jtfCity.getText().equals("")
                ||jtfPostalCode.getText().equals("")||jtfCountry.getText().equals("")||jtfPhone.getText().equals("")
                ||jtfFax.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar los campos");
        }else{
            Customers c = new Customers(jtfCustomerID.getText(),jtfCompanyName.getText(),jtfContactName.getText(),
                            jtfContactTitle.getText(),jtfAddress.getText(),jtfCity.getText(),jtfRegion.getText(),
                            jtfPostalCode.getText(),jtfCountry.getText(),jtfPhone.getText(),jtfFax.getText());
            if(cDAO.modificarRegistro(c)){
                JOptionPane.showMessageDialog(rootPane, "Datos modificados exitosamente");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudieron modificar los datos");
            }
            mostrarTabla(sqlC);
            }


    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        restablecerComponentes(jtfCustomerID1);
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CustomerDAO cDAO = new CustomerDAO();

        if(jtfCustomerID1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar el id del proveedor");
        }else{
            String id = jtfCustomerID1.getText();

            if(cDAO.borrarRegistro(id)) {
                JOptionPane.showMessageDialog(rootPane,"Se eliminó correctamente de la base de datos");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar eliminar a la base de datos");
            }

        }

        mostrarTabla(sqlC);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtfCustomerID1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerID1KeyReleased
        String filtro = jtfCustomerID1.getText();
        String sql =  "SELECT * FROM Customers WHERE CustomerID LIKE '"+filtro+"%'";
        mostrarTabla(sql);
    }//GEN-LAST:event_jtfCustomerID1KeyReleased

    private void jtfCustomerID1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerID1KeyPressed
        validacionLetras(evt, jtfCustomerID1);
    }//GEN-LAST:event_jtfCustomerID1KeyPressed

    private void jtfRegionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRegionKeyPressed
        validacionLetras(evt, jtfRegion);
    }//GEN-LAST:event_jtfRegionKeyPressed

    private void jtfAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAddressKeyPressed
        validacionString(evt, jtfAddress);
    }//GEN-LAST:event_jtfAddressKeyPressed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        restablecerComponentes(jtfCustomerID,jtfCompanyName,jtfContactName,jtfContactTitle,jtfAddress,jtfCity,jtfRegion,
                               jtfPostalCode,jtfCountry,jtfPhone,jtfFax);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        CustomerDAO cDAO = new CustomerDAO();
        if(jtfCustomerID.getText().equals("")|| jtfCompanyName.getText().equals("")||jtfContactName.getText().equals("")
                ||jtfContactTitle.getText().equals("")||jtfAddress.getText().equals("")||jtfCity.getText().equals("")
                ||jtfPostalCode.getText().equals("")||jtfCountry.getText().equals("")||jtfPhone.getText().equals("")
                ||jtfFax.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debes completar los campos");
        }else{
            Customers c = new Customers(jtfCustomerID.getText(),jtfCompanyName.getText(),jtfContactName.getText(),
                            jtfContactTitle.getText(),jtfAddress.getText(),jtfCity.getText(),jtfRegion.getText(),
                            jtfPostalCode.getText(),jtfCountry.getText(),jtfPhone.getText(),jtfFax.getText());
            System.out.println(c);
            if(cDAO.insertarRegistro(c)){
                JOptionPane.showMessageDialog(rootPane,"Se agregó correctamente a la base de datos");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Hubo un error al intentar agregar a la base de datos");
            }

        }
        mostrarTabla(sqlC);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtfPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhoneKeyReleased

    }//GEN-LAST:event_jtfPhoneKeyReleased

    private void jtfPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhoneKeyPressed
        validacionString(evt, jtfPhone);
    }//GEN-LAST:event_jtfPhoneKeyPressed

    private void jtfCountryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCountryKeyPressed
        validacionLetras(evt, jtfCountry);
    }//GEN-LAST:event_jtfCountryKeyPressed

    private void jtfCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCityKeyPressed
        validacionString(evt, jtfCity);
    }//GEN-LAST:event_jtfCityKeyPressed

    private void jtfContactTitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactTitleKeyPressed
        validacionLetras(evt, jtfContactTitle);
    }//GEN-LAST:event_jtfContactTitleKeyPressed

    private void jtfContactNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactNameKeyPressed
        validacionLetras(evt, jtfContactName);
    }//GEN-LAST:event_jtfContactNameKeyPressed

    private void jtfCompanyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyNameKeyPressed
        validacionLetras(evt, jtfCompanyName);
    }//GEN-LAST:event_jtfCompanyNameKeyPressed

    private void jtfCustomerIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerIDKeyTyped

    private void jtfCustomerIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerIDKeyPressed
        validacionLetras(evt, jtfCustomerID);
    }//GEN-LAST:event_jtfCustomerIDKeyPressed

    private void jtfCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerIDActionPerformed

    private void jtfPostalCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPostalCodeKeyPressed
        validacionNumeros(evt, jtfPostalCode, 5);
    }//GEN-LAST:event_jtfPostalCodeKeyPressed

    private void jtfFaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFaxKeyPressed
        validacionString(evt, jtfFax);
    }//GEN-LAST:event_jtfFaxKeyPressed

    private void jtfFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFaxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFaxKeyReleased

    private void jtfCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyNameActionPerformed

    private void jtfCustomerID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCustomerID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerID2ActionPerformed

    private void jtfCustomerID2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerID2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerID2KeyPressed

    private void jtfCustomerID2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerID2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerID2KeyTyped

    private void jtfCompanyName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName2ActionPerformed

    private void jtfCompanyName2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyName2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName2KeyPressed

    private void jtfContactName2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactName2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactName2KeyPressed

    private void jtfContactTitle2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactTitle2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactTitle2KeyPressed

    private void jtfAddress2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAddress2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddress2KeyPressed

    private void jtfCity2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCity2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCity2KeyPressed

    private void jtfRegion2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRegion2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRegion2KeyPressed

    private void jtfPostalCode2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPostalCode2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPostalCode2KeyPressed

    private void jtfCountry2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCountry2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCountry2KeyPressed

    private void jtfPhone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhone2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone2KeyPressed

    private void jtfPhone2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhone2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone2KeyReleased

    private void jtfFax2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFax2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFax2KeyPressed

    private void jtfFax2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFax2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFax2KeyReleased

    private void jtfCustomerID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCustomerID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerID3ActionPerformed

    private void jtfCustomerID3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerID3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerID3KeyPressed

    private void jtfCustomerID3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCustomerID3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCustomerID3KeyTyped

    private void jtfCompanyName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName3ActionPerformed

    private void jtfCompanyName3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyName3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyName3KeyPressed

    private void jtfContactName3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactName3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactName3KeyPressed

    private void jtfContactTitle3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactTitle3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactTitle3KeyPressed

    private void jtfAddress3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAddress3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddress3KeyPressed

    private void jtfCity3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCity3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCity3KeyPressed

    private void jtfRegion3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRegion3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRegion3KeyPressed

    private void jtfPostalCode3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPostalCode3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPostalCode3KeyPressed

    private void jtfCountry3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCountry3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCountry3KeyPressed

    private void jtfPhone3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhone3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone3KeyPressed

    private void jtfPhone3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPhone3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPhone3KeyReleased

    private void jtfFax3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFax3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFax3KeyPressed

    private void jtfFax3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFax3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFax3KeyReleased

    
    public void restablecerComponentes(Component...componentesGraficos) {
	for (Component c: componentesGraficos) {
            if (c instanceof JComboBox) {
		((JComboBox<?>)c).setSelectedIndex(0);
            }else if (c instanceof JTextField) {
		((JTextField)c).setText("");
            }
        }
    }

    
    public void mostrarTabla(String sql){
        ResultSetTableModel modeloDatos = null;
        String url = "jdbc:sqlserver://localhost:1433;databaseName=Northwind;"
                    + "user=Ruby;"
                    + "password=aguacate;"
                    + "encrypt=true;trustServerCertificate=true;";
        
	try {
            modeloDatos = new ResultSetTableModel("com.microsoft.sqlserver.jdbc.SQLServerDriver",url,sql);
	} catch (ClassNotFoundException e1) {
            e1.printStackTrace();
	} catch (SQLException e1) {
            e1.printStackTrace();
	}
        jScrollPane1.getViewport().remove(jTable1);
        jTable1 = new JTable(modeloDatos);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obtenerRegistroTabla();
            }
        });
        jScrollPane1.getViewport().add(jTable1);
        
    }
    
    
    public void obtenerRegistroTabla(){
        jtfCustomerID.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        jtfCustomerID1.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        jtfCustomerID2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        jtfCustomerID3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
        
        jtfCompanyName.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        jtfCompanyName2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        jtfCompanyName3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),1));
        
        jtfContactName.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        jtfContactName2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        jtfContactName3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),2));
        
        jtfContactTitle.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        jtfContactTitle2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        jtfContactTitle3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),3));
        
        jtfAddress.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),4));
        jtfAddress2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),4));
        jtfAddress3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),4));
        
        jtfCity.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),5));
        jtfCity2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),5));
        jtfCity3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),5));
        
        jtfRegion.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),6));
        jtfRegion2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),6));
        jtfRegion3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),6));
        
        jtfPostalCode.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),7));
        jtfPostalCode2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),7));
        jtfPostalCode3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),7));

        jtfCountry.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),8));
        jtfCountry2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),8));
        jtfCountry3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),8));

        jtfPhone.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),9));
        jtfPhone2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),9));
        jtfPhone3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),9));

        jtfFax.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),10));
        jtfFax2.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),10));
        jtfFax3.setText(""+jTable1.getValueAt(jTable1.getSelectedRow(),10));

    }
    
    
    public String obtenerFecha(JComboBox dia,JComboBox mes,JComboBox año){
        String d = (String) dia.getSelectedItem();
        String m = (String) mes.getSelectedItem();
        String a = (String) año.getSelectedItem();
        return a+"-"+m+"-"+d;
    }
    
    
    public void validacionLetras(KeyEvent evt, JTextField jtf){  
        char car = evt.getKeyChar();
	if(Character.isLetter(car)||(car==KeyEvent.VK_BACK_SPACE)){
            jtf.setEditable(true);
        }else{
            jtf.setEditable(false);
        }
    }
    
    public void validacionNumeros(KeyEvent evt, JTextField jtf, int lim){
        int code=evt.getKeyCode();    
        if (((evt.getKeyChar() >= '0'&&evt.getKeyChar() <= '9'))&&jtf.getText().length()<lim||(code==KeyEvent.VK_BACK_SPACE)) {
            jtf.setEditable(true);
        }else{
            jtf.setEditable(false);
        }  
    }
    
    public void validacionString(KeyEvent evt, JTextField jtf){
        int code = evt.getKeyCode();
        int limite = 20;
        if ((jtf.getText().equals("")?true:!(jtf.getText().charAt(jtf.getText().length()-1)==' '&&code==KeyEvent.VK_SPACE))&&(jtf.getText().length()<limite||code==KeyEvent.VK_BACK_SPACE)) {
                jtf.setEditable(true);
        }else{
                jtf.setEditable(false);
        }
    }
    
    
    
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel Address3;
    private javax.swing.JLabel City;
    private javax.swing.JLabel City2;
    private javax.swing.JLabel City3;
    private javax.swing.JLabel CompanyName;
    private javax.swing.JLabel CompanyName2;
    private javax.swing.JLabel CompanyName3;
    private javax.swing.JLabel ContactName;
    private javax.swing.JLabel ContactName2;
    private javax.swing.JLabel ContactName3;
    private javax.swing.JLabel ContactTitle;
    private javax.swing.JLabel ContactTitle2;
    private javax.swing.JLabel ContactTitle3;
    private javax.swing.JLabel Country;
    private javax.swing.JLabel Country2;
    private javax.swing.JLabel Country3;
    private javax.swing.JLabel CustomerID;
    private javax.swing.JLabel CustomerID1;
    private javax.swing.JLabel CustomerID2;
    private javax.swing.JLabel CustomerID3;
    private javax.swing.JLabel Fax;
    private javax.swing.JLabel Fax2;
    private javax.swing.JLabel Fax3;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Phone2;
    private javax.swing.JLabel Phone3;
    private javax.swing.JLabel PostalCode;
    private javax.swing.JLabel PostalCode2;
    private javax.swing.JLabel PostalCode3;
    private javax.swing.JLabel Region;
    private javax.swing.JLabel Region2;
    private javax.swing.JLabel Region3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnBorrar3;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpAltas;
    private javax.swing.JPanel jpBajas;
    private javax.swing.JPanel jpCambios;
    private javax.swing.JPanel jpConsultas;
    private javax.swing.JPanel jpTabla;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfAddress2;
    private javax.swing.JTextField jtfAddress3;
    private javax.swing.JTextField jtfCity;
    private javax.swing.JTextField jtfCity2;
    private javax.swing.JTextField jtfCity3;
    private javax.swing.JTextField jtfCompanyName;
    private javax.swing.JTextField jtfCompanyName2;
    private javax.swing.JTextField jtfCompanyName3;
    private javax.swing.JTextField jtfContactName;
    private javax.swing.JTextField jtfContactName2;
    private javax.swing.JTextField jtfContactName3;
    private javax.swing.JTextField jtfContactTitle;
    private javax.swing.JTextField jtfContactTitle2;
    private javax.swing.JTextField jtfContactTitle3;
    private javax.swing.JTextField jtfCountry;
    private javax.swing.JTextField jtfCountry2;
    private javax.swing.JTextField jtfCountry3;
    private javax.swing.JTextField jtfCustomerID;
    private javax.swing.JTextField jtfCustomerID1;
    private javax.swing.JTextField jtfCustomerID2;
    private javax.swing.JTextField jtfCustomerID3;
    private javax.swing.JTextField jtfFax;
    private javax.swing.JTextField jtfFax2;
    private javax.swing.JTextField jtfFax3;
    private javax.swing.JTextField jtfPhone;
    private javax.swing.JTextField jtfPhone2;
    private javax.swing.JTextField jtfPhone3;
    private javax.swing.JTextField jtfPostalCode;
    private javax.swing.JTextField jtfPostalCode2;
    private javax.swing.JTextField jtfPostalCode3;
    private javax.swing.JTextField jtfRegion;
    private javax.swing.JTextField jtfRegion2;
    private javax.swing.JTextField jtfRegion3;
    private javax.swing.JTabbedPane jtpContenidoABCC;
    // End of variables declaration//GEN-END:variables
}
